### PR TITLE
Add CR validation webhook

### PR DESCRIPTION
**Pull request by cuttingedge1109**
In addition, added template rendering frequency per CR

### CODE REVIEW

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/e27cdd9ebbba2f3cf30d531c5d056734d7999097/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Konfigurator:SNAPSHOT-PR-53-95628d81`

**Comment by stakater-user** [comment]
@cuttingedge1109 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Konfigurator:SNAPSHOT-PR-53-c679b492`

**Comment by stakater-user** [comment]
@cuttingedge1109 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Konfigurator:SNAPSHOT-PR-53-973990bc`

**Comment by rasheedamir** [comment]
@cuttingedge1109 can we add some tests for this new code?

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/e84da5469885c5a438fc4c38f0eb919f12d11226/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Konfigurator:SNAPSHOT-PR-53-36dcc949`

**Comment by stakater-user** [comment]
@cuttingedge1109 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Konfigurator:SNAPSHOT-PR-53-617d8ddf`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
