### PR TITLE
update operator sdk

### PR DESCRIPTION
**Pull request by cuttingedge1109**

### CODE REVIEW

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/b4cdd080336c931205ed25c905cfce53aa1395df/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/17e916e989615c0ca4b22aa9f25413080a74675c/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/7745b8c8a142664318368686f7b59e8a236470c4/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/285ad47b8e8a2b8480305f5fcf360798959d46db/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/45d5f00d804bea52753d11da6c018a4b3ae984b2/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/51bfe7e210c8ce4963e62d4eacdf8e5bc9289449/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Konfigurator:SNAPSHOT-PR-52-f9ce10f6`

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/17fe06ffdfae818c520340516022c10a0eb1cef2/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/10a2da29947790fbc09b61ea569669cdd7a4f378/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Konfigurator:SNAPSHOT-PR-52-c99dde39`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
