### PR TITLE
Update ingress API group from extensionsv1beta1 to networkingv1 to comply with k8s >= v1.22

### PR DESCRIPTION
**Pull request by usamaahmadkhan**

### CODE REVIEW

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/e50d054e28e2768d2afc0ad02c2b53673cb81a0c/checks) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/f9494b5bbd62d930bc29a7aded8f317a5208a358/checks) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/dddff9c5d614ddf3d76ef2f063fa820e77f7389b/checks) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/b4e114affa1e69ef44aa71544e396a01bd1a94c9/checks) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull stakater/Konfigurator:SNAPSHOT-PR-68-dc55c621`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull stakater/Konfigurator:SNAPSHOT-PR-68-3f0e6e2f`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull stakater/Konfigurator:SNAPSHOT-PR-68-17628d55`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull stakater/konfigurator:SNAPSHOT-PR-68-f9cca895`

**Review by tanalam2411 — APPROVED** [review]
LGTM

**Pull request merged**
