### PR TITLE
Update podmetadatainjector

### PR DESCRIPTION
**Pull request by cuttingedge1109**

### CODE REVIEW

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/4b5c60a170baca42600edf1f62bd76465b49e5b0/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Konfigurator:SNAPSHOT-PR-62-2b72c46e`

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/389b7d4721c9ebe7b7eed79cfa16d40a31efe8be/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Konfigurator/commit/7cb378a493b192e604bc8d5bfc9a432c646f9ec9/checks) has Failed!

**Comment by stakater-user** [comment]
@cuttingedge1109 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Konfigurator:SNAPSHOT-PR-62-77a1c416`

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
